### ISSUE TITLE
Minimum claims required for integration

### ISSUE THREAD

**Issue by alexchiraples** [gov-ithub/auth-sso#88]
In order to have consistent and, as much as possible, real data about the registered people, we need to gather some consistent data about the user. Bellow you can find a proposed list of minimum details an user needs to complete in order to be accepted by the system :

| Property   |      JWT Claim      |  Required | Comment|
|------------|:--------------|:-----------:|-|
| Email        |email|*||
| Name       |name|*||
| Gender     |gender|||
| Birthdate  |birthdate|*|Required for age verification?|
|Phone|phone_number| |Two factor authentication ?|
|County|a)|||
|City/Town|b)|||
|Street addr|c) -> (a,b,c) grouped under address claim|*||

- This list should be confronted with legal advisors in order to avoid collecting sensitive data.

**Comment by RePierre** [comment]
MSDN provides a [list of predefined claims](https://msdn.microsoft.com/en-us/library/system.identitymodel.claims.claimtypes(v=vs.110).aspx) and there is a distinction between `first name / given name`, `last name / surname` and `name` claims. IMHO we'd better require `GivenName` and `Surname` claims instead of just using `Name`.

Also, to avoid confusion from duplicate names we should take into consideration adding a claim for personal identification number (CNP).

**Comment by dmihaita** [comment]
I agree with first part of the proposal.
Regarding CNP, this is sensitive data, and I think that we are not allowed to collect it without authorization from ANSPDCP (http://dataprotection.ro/).
